# Generated by Django 5.2.1 on 2025-05-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courieruser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courieruser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
