# Generated by Django 5.2.1 on 2025-06-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_courieruser_latitude_courieruser_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courieruser',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='courieruser',
            name='total_ratings',
        ),
    ]
