# Generated by Django 5.2.1 on 2025-06-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_courieruser_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courieruser',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='courieruser',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
