# Generated by Django 4.2.21 on 2025-06-08 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='menu_item',
            new_name='food_item',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Accepted', 'Accepted'), ('Assigned', 'Assigned'), ('Picked Up', 'Picked Up'), ('Finish', 'Finish'), ('Done', 'Done'), ('Rejected', 'Rejected')], default='Created', max_length=20),
        ),
    ]
