# Generated by Django 4.2.21 on 2025-06-08 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_courieruser_latitude_courieruser_longitude'),
        ('order', '0002_rename_menu_item_orderitem_food_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='account.customeruser'),
        ),
    ]
