# Generated by Django 5.2.1 on 2025-06-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Accepted', 'Confirmed by Restaurant'), ('Assigned', 'Assigned to Courier'), ('Picked_Up', 'Picked Up'), ('Finish', 'Finish'), ('Done', 'Done')], default='Created', max_length=20),
        ),
    ]
