# Generated by Django 5.2.1 on 2025-06-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Accepted', 'Confirmed by Restaurant'), ('Assigned', 'Assigned to Courier'), ('Picked_Up', 'Picked Up'), ('Finish', 'Finish'), ('Done', 'Done'), ('Reject', 'Reject')], default='Created', max_length=20),
        ),
    ]
