# Generated by Django 5.2.1 on 2025-06-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cart_restaurant_alter_order_courier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
    ]
