# Generated by Django 4.2.21 on 2025-06-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
    ]
