# Generated by Django 4.2.21 on 2025-06-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_remove_fooditem_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodCategory',
            new_name='RestaurantCategory',
        ),
    ]
