# Generated by Django 4.2.21 on 2025-06-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_alter_restaurant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_items/'),
        ),
    ]
