# Generated by Django 4.2.21 on 2025-06-01 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_rename_foodcategory_restaurantcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantcategory',
            options={'verbose_name_plural': 'Restaurant Categories'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurant.restaurantcategory'),
        ),
    ]
