# Generated by Django 4.2.21 on 2025-06-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0005_alter_restaurantcategory_options_restaurant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantcategory',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
