# Generated by Django 4.2.21 on 2025-06-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0006_restaurantcategory_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantCategory',
            new_name='FoodCategory',
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name_plural': 'Food Categories'},
        ),
    ]
